### ISSUE TITLE
"Мовний закон є порушенням прав громадянина" додає не в ту сторону

### ISSUE THREAD

**Issue by ghost** [Wlad1slav/ukrainianvalues.github.io#2]
Якщо натиснути "Повністю Згодний", то позиція щодо мови йде в сторону державної:

<img width="777" alt="Screenshot 2024-03-20 at 12 43 36" src="https://github.com/Wlad1slav/ukrainianvalues.github.io/assets/13499243/99972a15-bdb3-43e5-bc43-64a77231c807">

**Comment by RadDiko** [comment]
Дякую за уважність. Виправив
