### ISSUE TITLE
Повернення назад спричинаяє подвійне голосування

### ISSUE THREAD

**Issue by viktor-yakubiv** [Wlad1slav/ukrainianvalues.github.io#5]
Відповідно то поточного стану коду, `next_question` автоматично домножує результати, але повернення до попереднього питання не скасовує цієї зміни. Відповідно поверення й голосування ще раз створює повторний голос.

**Comment by VincentWild69** [comment]
Ні, це не так, подивіться уважно. Там при поверненні змінюється номер питання і по цьому індексу в массиві перезаписується старе значення. Все працює корректно.

**Comment by viktor-yakubiv** [comment]
@VincentWild69 все точно, як ви кажете. Перепрошую, недогледів
